---

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yaml"
    - "../vars/{{ ansible_distribution }}.yaml"
    - "../vars/{{ ansible_os_family }}.yaml"
    - "../vars/default.yaml"
  # when: squid_package_name is not defined or squid_service_name is not defined
