- block:

    - name: "Start Postfix Service"
      service:
       name: "{{ postfix_service }}"
       state: started
       enabled: yes

    - name: "Restart Postfix Service"
      service:
       name: "{{ postfix_service }}"
       state: restarted
       
    - name: "Generate sasl.db"
      shell: "postmap /etc/postfix/sasl/sasl_passwd"

  become: true